### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Syna-20** [MuhammadMoinFaisal/Computervisionprojects#1]
I am trying to implement this code in google colab, but I am repeatedly being shown the following error-
![image](https://user-images.githubusercontent.com/101783446/236993211-d6a20f52-7192-45ac-88c8-09323d05e648.png)
Despite of following the notebook having the implementation for sign detection.

**Comment by MuhammadMoinFaisal** [comment]
Please restart run time after installing packages and then import libraries
